image: python:3.7-stretch

cache:
    paths:
      - .venv
    untracked: true

stages:
  - base_test
  - additional_tests
  - upload

variables:
  CACHE_NAME: $CI_PIPELINE_ID
  PACKAGE_NAME: aiohug


base_test_python_3.6:
  image: python:3.6-stretch
  stage: base_test
  script:
    - make pip_install
    - make ci_test

base_test_python_3.7:
  image: python:3.7-stretch
  stage: base_test
  script:
    - make pip_install
    - make ci_test
  artefacts:
    paths:
      - .reports

base_test_python_3.6_aiohttp_3.1:
  image: python:3.6-stretch
  stage: additional_tests
  script:
    - make pip_install
    - pip install aiohttp==3.1
    - make ci_test

base_test_python_3.6_aiohttp_3.4.4:
  image: python:3.6-stretch
  stage: additional_tests
  script:
    - make pip_install
    - pip install aiohttp==3.4.4
    - make ci_test

.pypi: &upload_base
  stage: upload
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  when: on_success
  environment:
    name: pypi.org
    url: https://pypi.org/$PACKAGE_NAME

upload:development:
  <<: *upload_base
  variables:
    DEV_VERSION: $CI_PIPELINE_ID
  when: manual

upload:production:
  <<: *upload_base
  only:
    - tags
