image: python:3.7-stretch

cache:
    paths:
      - .venv
    untracked: true

stages:
  - tests
  - upload

variables:
  CACHE_NAME: $CI_PIPELINE_ID
  PACKAGE_NAME: aiohug

tests_aiohttp_2.3:
  image: python:3.6-stretch
  stage: tests
  script:
    - make pip_install
    - pip install aiohttp==2.3.10
    - make ci_test

tests_aiohttp_3.1.3:
  image: python:3.6-stretch
  stage: tests
  script:
    - make pip_install
    - pip install aiohttp==3.1.3
    - make ci_test

tests_aiohttp_3.4.4:
  image: python:3.6-stretch
  stage: tests
  script:
    - make pip_install
    - pip install aiohttp==3.4.4
    - make ci_test

tests_python36:
  image: python:3.6-stretch
  stage: tests
  script:
    - make pip_install
    - make ci_test

tests_python37:
  image: python:3.7-stretch
  stage: tests
  script:
    - make pip_install
    - make ci_test

.pypi: &upload_base
  stage: upload
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  when: on_success
  environment:
    name: pypi.org
    url: https://pypi.org/$PACKAGE_NAME

upload:development:
  <<: *upload_base
  variables:
    DEV_VERSION: $CI_PIPELINE_ID
  except:
    - tags

upload:production:
  <<: *upload_base
  only:
    - tags
