image: python:3.7-stretch

cache:
  paths:
    - .venv
  untracked: true

stages:
  - tests
  - upload

variables:
  CACHE_NAME: $CI_PIPELINE_ID
  PACKAGE_NAME: aiohug

tests_python_3.6:
  image: python:3.6-stretch
  stage: tests
  script:
    - make pip_install
    - make ci_test
    - coveralls

tests_python_3.7:
  image: python:3.7-stretch
  stage: tests
  script:
    - make pip_install
    - make ci_test
    - coveralls
  artifacts:
    paths:
      - .reports
    expire_in: 1 week

tests_python_3.6_aiohttp_3.1:
  image: python:3.6-stretch
  stage: tests
  script:
    - make pip_install
    - pip install aiohttp==3.1
    - make ci_test

tests_python_3.6_aiohttp_3.4.4:
  image: python:3.6-stretch
  stage: tests
  script:
    - make pip_install
    - pip install aiohttp==3.4.4
    - make ci_test

.pypi: &upload_base
  stage: upload
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  when: on_success
  environment:
    name: pypi.org
    url: https://pypi.org/$PACKAGE_NAME

upload:development:
  <<: *upload_base
  variables:
    DEV_VERSION: $CI_PIPELINE_ID
  when: manual

upload:production:
  <<: *upload_base
  only:
    - tags
