image: python:3.6-stretch

stages:
  - tests
  - upload

variables:
  CACHE_NAME: $CI_PIPELINE_ID
  PACKAGE_NAME: aiohug

tests_python36:
  stage: tests
  script:
    - make test_coverage PYTHON_VERSION=3.6
  artifacts:
    paths:
      - .coverage
    expire_in: 1d

tests_python37:
  image: python:3.7-stretch
  stage: tests
  script:
    - make test_coverage PYTHON_VERSION=3.7
  artifacts:
    paths:
      - .coverage
    expire_in: 1d
